# Generated by Django 4.1.2 on 2022-11-01 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='institution',
            new_name='inst_num',
        ),
        migrations.RenameField(
            model_name='bank',
            old_name='swiftcode',
            new_name='swift_code',
        ),
        migrations.AddField(
            model_name='bank',
            name='branches',
            field=models.ManyToManyField(default=[], to='banks.branch'),
        ),
        migrations.AddField(
            model_name='bank',
            name='owner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
