# Generated by Django 4.1.2 on 2022-11-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0002_rename_institution_bank_inst_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='branches',
            field=models.ManyToManyField(blank=True, to='banks.branch'),
        ),
    ]
