# Generated by Django 4.1.2 on 2022-11-01 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0003_alter_bank_branches'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='transitnumber',
            new_name='transit_num',
        ),
    ]
