# Generated by Django 4.1.2 on 2022-11-01 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('banks', '0006_alter_bank_description_alter_bank_inst_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
