# Generated by Django 4.1.2 on 2022-11-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0008_remove_bank_branches_bank_branches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='branches',
        ),
        migrations.AddField(
            model_name='bank',
            name='branches',
            field=models.ManyToManyField(blank=True, null=True, to='banks.branch'),
        ),
    ]
