# Generated by Django 4.1.2 on 2022-11-01 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0010_alter_bank_branches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='branches',
        ),
        migrations.AddField(
            model_name='bank',
            name='branches',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='banks.branch'),
        ),
    ]
