# Generated by Django 4.1.2 on 2022-11-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0012_remove_bank_branches_branch_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
